security:
  oauth2:
    client:
      client-id: pepe
      client-secret: pepe

#spring:
#  profiles:
#    active: dev, pro, it

spring:
  security:
    user:
      password: pwd

  profiles:
    active: dev